MODEL:
  WEIGHTS: null
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
dino:
  loss_weight: 1.0
  head_n_prototypes: 128
  head_bottleneck_dim: 64
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: false
  head_n_prototypes: 128
  head_bottleneck_dim: 64 
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  batch_size_per_gpu: 64
  dataset_path: "AstroClipDataset:split=train:root=/workspace/astroclip/data/legacy_desi_set"
  columns:
  - image
  output_dir: /workspace/astroclip/results/
  saveckp_freq: 20
  seed: 0
  num_workers: 16
  OFFICIAL_EPOCH_LENGTH: 2500
  cache_dataset: true
  centering: "centering" # or "sinkhorn_knopp"
student:
  arch: swinv2
  img_size: 144
  patch_size: 12
  embed_dim: 1024
  depths: [6,6]  # Only 2 layers instead of 3
  num_heads: [16, 32] # Match the number of layers
  window_size: 3
  mlp_ratio: 4.0
  drop:  0.1
  drop_path_rate: 0.1 
teacher:
  momentum_teacher: 0.996
  final_momentum_teacher: 0.999
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 2
optim:
  epochs: 20
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 1.25e-05  
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 2
  min_lr: 2.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.1
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crops_scale:
  - 0.8
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.4
  - 0.6
  global_crops_size: 144 # 
  local_crops_size: 72 # 
evaluation:
  eval_period_iterations: 1000
